[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "10.8.2"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["utils/**"]
  node_bundler = "esbuild"
  external_node_modules = ["@pinata/sdk", "axios"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "next"
  targetPort = 3000 