[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "10.8.2"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["utils/**"]
  node_bundler = "esbuild"
  external_node_modules = ["@pinata/sdk", "axios"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-server-handler"
  status = 200
  force = true

[dev]
  framework = "next"
  targetPort = 3000 